[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
riddle_rush = "Gb4JYubKArC3R3EpQSzYwoPecYBNi2znUmtHrhLNeVsM"

[programs.devnet]
riddle_rush = "Gb4JYubKArC3R3EpQSzYwoPecYBNi2znUmtHrhLNeVsM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize = "yarn run ts-node scripts/initialize.ts"
